### ISSUE TITLE
gulp serve

### ISSUE THREAD

**Issue by guoyoujin** [jackhutu/jackblog-angular1#3]
执行gulp serve后，报如下错误，关键是我已经安装好了所有的插件，包括ruby的插件我都已经安装完毕，请问你碰到过这个问题吗？
```````
gulp serve
[13:19:12] Using gulpfile ~/NodeJs/jackblog-angular1/gulpfile.js
[13:19:12] Starting 'dev-config'...
[13:19:12] Starting 'scripts'...
[13:19:12] Starting 'inject_sass'...
[13:19:12] gulp-inject 6 files into index.scss.
[13:19:12] Finished 'dev-config' after 342 ms
[13:19:12] Finished 'inject_sass' after 194 ms
[13:19:12] Starting 'styles:compass'...
[13:19:13] /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:91:in `expand_path': Insecure operation - expand_path (SecurityError)
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:91:in `extension_dir'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb:144:in `missing_extensions?'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1037:in `block in find_by_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `each'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `find'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `find_by_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:189:in `try_activate'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/guoyoujin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:9:in `<main>'

[13:19:13] Error in plugin 'gulp-compass'
Message:
    Compass failed
[13:19:13] all files 34.03 kB
[13:19:13] Finished 'scripts' after 829 ms
```````

**Comment by jackhutu** [comment]
什么环境?  以及分别运行```sass -v``` ```compass -v``` 显示什么?

**Comment by guoyoujin** [comment]
`````
guoyoujin ☁️  Tongxin-Mac: ~/NodeJs/jackblog-angular1(master) ➡️  sass -v
Sass 3.4.22 (Selective Steve)
guoyoujin ☁️  Tongxin-Mac: ~/NodeJs/jackblog-angular1(master) ➡️  compass -v 
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2016 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
`````

**Comment by guoyoujin** [comment]
感觉应该没什么问题吧，我ruby使用的是2.2.2版本，不知道有没有影响，不过2.2.0版本我也试过也抱着个错误，

还有就是我的node使用的版本是v5.10.1，不过这个错误跟node不知道有没有关系

**Comment by jackhutu** [comment]
我的开发环境也是mac os, 没遇到你这样的问题, 你查一下是不是环境变量有问题, 另外安装gulp-compass有没有报错.

**Comment by guoyoujin** [comment]
你所说的环境变量是ruby的环境变量吗？，这个是我配置的rvm环境变量
````````
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
````````

**Comment by jackhutu** [comment]
没问题啊, 注释掉https://github.com/jackhutu/jackblog-angular1/blob/master/src/app/!base.scss 第2到22行, 再运行gulp serve 试试

**Comment by guoyoujin** [comment]
试了下还是不行，问下你用的ruby版本是多少啊

**Comment by jackhutu** [comment]
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

**Comment by guoyoujin** [comment]
我用的2.2.2应该没什么问题啊，头疼，感觉这个问题无解了

**Comment by guoyoujin** [comment]
这个插件compass用到的多吗？是否可以把它去掉呢

**Comment by jackhutu** [comment]
可以安装```bower install jackblog-sass```这个编译好的css包, 然后就可以去掉所有的scss文件和相关gulp任务, compass也就不用装了.

**Comment by guoyoujin** [comment]
👍确实跑起来了，非常棒，不过样式没有注入进去，我先研究研究，非常🙏

**Comment by guoyoujin** [comment]
oh my god！
终于解决这个问题了，原来根本原因就是要加上sudo命令安装，
``````````
sudo gem install compass
sudo gulp serve
``````````
即可，纠结

**Comment by jackhutu** [comment]
好. 加油.
